"""Add stripe_id to users table

Revision ID: 10dce564cfe5
Revises: afd915402f7
Create Date: 2014-10-05 20:25:32.138200

"""

# revision identifiers, used by Alembic.
revision = '10dce564cfe5'
down_revision = 'afd915402f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_id')
    ### end Alembic commands ###
