"""Add ReplayAlias

Revision ID: 13915d3bce04
Revises: ddf8cb2d4e1
Create Date: 2014-06-20 20:52:48.772073

"""

# revision identifiers, used by Alembic.
revision = '13915d3bce04'
down_revision = 'ddf8cb2d4e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('alias', sa.String(length=96), nullable=False),
    sa.Column('replay_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replay_alias')
    ### end Alembic commands ###
