"""Persist League data to database

Revision ID: 20419983cbfd
Revises: c303c34832f
Create Date: 2014-09-21 16:11:35.211785

"""

# revision identifiers, used by Alembic.
revision = '20419983cbfd'
down_revision = 'c303c34832f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tournament_url', sa.String(length=255), nullable=True),
    sa.Column('itemdef', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_url_large', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(u'ix_league_views_league_id', table_name='league_views')
    op.drop_index(u'ix_replays_league_id', table_name='replays')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_replays_league_id', 'replays', [u'league_id'], unique=False)
    op.create_index(u'ix_league_views_league_id', 'league_views', [u'league_id'], unique=False)
    op.drop_table('leagues')
    ### end Alembic commands ###
