"""Add LeagueView model - basically subcategories for league pages

Revision ID: 25cd1f4d609
Revises: 13915d3bce04
Create Date: 2014-07-09 21:53:28.142996

"""

# revision identifiers, used by Alembic.
revision = '25cd1f4d609'
down_revision = '13915d3bce04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'league_id')
    )
    op.create_table('league_view_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_view_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.Enum('greater_than_equals', 'greater_than', 'less_than_equals', 'less_than', 'equals', 'not_equals', 'in', 'not_in'), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['league_view_id'], ['league_views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_view_filter')
    op.drop_table('league_views')
    ### end Alembic commands ###
