"""Add ReplayAutoFix model to log automagic fix attempts

Revision ID: 56ab5cddf8a5
Revises: 20419983cbfd
Create Date: 2014-09-28 14:29:09.749529

"""

# revision identifiers, used by Alembic.
revision = '56ab5cddf8a5'
down_revision = '20419983cbfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_auto_fix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('replay_id', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_replay_auto_fix_error', 'replay_auto_fix', ['error'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_replay_auto_fix_error', table_name='replay_auto_fix')
    op.drop_table('replay_auto_fix')
    ### end Alembic commands ###
