"""Tweaks to subscription table for Stripe subscriptions

Revision ID: afd915402f7
Revises: d24bbbf0e3d
Create Date: 2014-10-05 15:40:18.896593

"""

# revision identifiers, used by Alembic.
revision = 'afd915402f7'
down_revision = 'd24bbbf0e3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('plan_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'plan_id')
    op.drop_column('subscription', 'auto_renew')
    ### end Alembic commands ###
