"""ADD A BUNCH OF INDEXES

Revision ID: c303c34832f
Revises: 25cd1f4d609
Create Date: 2014-09-20 14:56:35.525044

"""

# revision identifiers, used by Alembic.
revision = 'c303c34832f'
down_revision = '25cd1f4d609'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_gc_jobs_timestamp', 'gc_jobs', ['timestamp'], unique=False)
    op.create_index(u'ix_gc_jobs_type', 'gc_jobs', ['type'], unique=False)
    op.alter_column('gc_workers', 'password',
               existing_type=sa.BLOB(),
               nullable=False)
    op.create_index(u'ix_league_views_league_id', 'league_views', ['league_id'], unique=False)
    op.create_index(u'ix_league_views_menu_order', 'league_views', ['menu_order'], unique=False)
    op.create_index(u'ix_logs_level', 'logs', ['level'], unique=False)
    op.create_index(u'ix_logs_resolved_by_user_id', 'logs', ['resolved_by_user_id'], unique=False)
    op.create_index(u'ix_replay_alias_updated_at', 'replay_alias', ['updated_at'], unique=False)
    op.create_index(u'ix_replay_players_account_id', 'replay_players', ['account_id'], unique=False)
    op.create_index(u'ix_replay_players_hero_id', 'replay_players', ['hero_id'], unique=False)
    op.create_index(u'ix_replay_ratings_positive', 'replay_ratings', ['positive'], unique=False)
    op.create_index(u'ix_replays_added_to_site_time', 'replays', ['added_to_site_time'], unique=False)
    op.create_index(u'ix_replays_dire_team_id', 'replays', ['dire_team_id'], unique=False)
    op.create_index(u'ix_replays_dire_team_name', 'replays', ['dire_team_name'], unique=False)
    op.create_index(u'ix_replays_dl_done_time', 'replays', ['dl_done_time'], unique=False)
    op.create_index(u'ix_replays_game_mode', 'replays', ['game_mode'], unique=False)
    op.create_index(u'ix_replays_gc_done_time', 'replays', ['gc_done_time'], unique=False)
    op.create_index(u'ix_replays_league_id', 'replays', ['league_id'], unique=False)
    op.create_index(u'ix_replays_local_uri', 'replays', ['local_uri'], unique=False)
    op.create_index(u'ix_replays_radiant_team_id', 'replays', ['radiant_team_id'], unique=False)
    op.create_index(u'ix_replays_radiant_team_name', 'replays', ['radiant_team_name'], unique=False)
    op.create_index(u'ix_replays_replay_state', 'replays', ['replay_state'], unique=False)
    op.create_index(u'ix_replays_state', 'replays', ['state'], unique=False)
    op.create_index(u'ix_searches_created_at', 'searches', ['created_at'], unique=False)
    op.create_index(u'ix_subscription_expires_at', 'subscription', ['expires_at'], unique=False)
    op.create_index(u'ix_users_first_seen', 'users', ['first_seen'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_first_seen', table_name='users')
    op.drop_index(u'ix_subscription_expires_at', table_name='subscription')
    op.drop_index(u'ix_searches_created_at', table_name='searches')
    op.drop_index(u'ix_replays_state', table_name='replays')
    op.drop_index(u'ix_replays_replay_state', table_name='replays')
    op.drop_index(u'ix_replays_radiant_team_name', table_name='replays')
    op.drop_index(u'ix_replays_radiant_team_id', table_name='replays')
    op.drop_index(u'ix_replays_local_uri', table_name='replays')
    op.drop_index(u'ix_replays_league_id', table_name='replays')
    op.drop_index(u'ix_replays_gc_done_time', table_name='replays')
    op.drop_index(u'ix_replays_game_mode', table_name='replays')
    op.drop_index(u'ix_replays_dl_done_time', table_name='replays')
    op.drop_index(u'ix_replays_dire_team_name', table_name='replays')
    op.drop_index(u'ix_replays_dire_team_id', table_name='replays')
    op.drop_index(u'ix_replays_added_to_site_time', table_name='replays')
    op.drop_index(u'ix_replay_ratings_positive', table_name='replay_ratings')
    op.drop_index(u'ix_replay_players_hero_id', table_name='replay_players')
    op.drop_index(u'ix_replay_players_account_id', table_name='replay_players')
    op.drop_index(u'ix_replay_alias_updated_at', table_name='replay_alias')
    op.drop_index(u'ix_logs_resolved_by_user_id', table_name='logs')
    op.drop_index(u'ix_logs_level', table_name='logs')
    op.drop_index(u'ix_league_views_menu_order', table_name='league_views')
    op.drop_index(u'ix_league_views_league_id', table_name='league_views')
    op.alter_column('gc_workers', 'password',
               existing_type=sa.BLOB(),
               nullable=True)
    op.drop_index(u'ix_gc_jobs_type', table_name='gc_jobs')
    op.drop_index(u'ix_gc_jobs_timestamp', table_name='gc_jobs')
    ### end Alembic commands ###
